Add controllers
MaxiTrue/java-shareit pull request #1
Opened 2022-07-10 19:41 UTC by MaxiTrue

Создан каркас приложения. Написана логика под классы User и Item

2022-07-11 05:04 UTC, eugene-lenkevich requested changes
Привет, Максим, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-11 05:04 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        User user = userStorage.getById(userId)
Мне кажется что тут объект-маппер занимается немного не своими обязанностями. Обязанность маппера - преобразовывать один объект в другой, а вот запросы в хранилище больше подходят для объекта-сервиса.
Но то что маппер сделан в виде спрингового бина - это правильно :)

2022-07-11 05:04 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +                .collect(Collectors.toList());
Если мы предполагаем что эмейл уникален (а судя по коду так и есть), тот тут можно сделать проще   :) 
return users.values().stream()
   .filter(user1 -> user1.getEmail().equals(email))
   .findFirst();

2022-07-11 05:04 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        if (!method.equals("POST")) {
В общем случае сервис не должен знать из какой среды его вызывают, в данном случае есть четкая зависимость от web. Причем можно заметить что код не универсален и зависит от конкретного кейса использования - от места вызова :)

2022-07-12 16:44 UTC, MaxiTrue commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +                .collect(Collectors.toList());
Исправлено

2022-07-12 18:58 UTC, MaxiTrue commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        if (!method.equals("POST")) {
Исправлено

2022-07-13 03:05 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-07-22 19:00 UTC, merged